Bug-fix: delete child tables before deleting parent for client.
delta/DAuth-Backend pull request #12
Opened 2021-07-16 18:49 UTC by nishihere19

Signed-off-by: Nishi Agrawal <nishihere19@gmail.com>

2021-08-07 14:42 UTC, AananthV requested changes

2021-08-07 14:42 UTC, AananthV commented on src/controllers/clientController.ts
> +        }
Can you wrap this in a Promise.all([])

2021-08-08 06:59 UTC, nishihere19 commented on src/controllers/clientController.ts
> +        }
Yes, will do

2021-08-13 16:01 UTC, AananthV approved these changes

2021-08-13 16:02 UTC, merged