Add: PKCE flow for android native
delta/DAuth-Backend pull request #22
Opened 2021-11-03 06:34 UTC by nishihere19

Signed-off-by: nishihere19 <nishihere19@gmail.com>

Fixes #

## Short description of the Issue.
PKCE for android apps

## Proposed Changes

  - Added the PKCE flow for android apps
  -The query params are optional and authorization works normally for the web clients.

2021-11-05 18:21 UTC, siva2204 requested changes
PKCE is to safe the native apps from authorization **code interception**.

so the code (code_verifier) should be verified in token route i.e while client exchange authorization code for a token.

- [flow digram](https://datatracker.ietf.org/doc/html/rfc7636#section-1.1)
- [complete-protocol](https://datatracker.ietf.org/doc/html/rfc7636#section-1.1)

we should save code_challenge,code_challenge_method linked to the authorization_code in server side(preferably db) and these saved code_challenge should be used to authorize when client asks for token in exchange of authorization code.

2021-11-05 18:21 UTC, siva2204 commented on src/routes/oauth.ts
> +// code_challenge_verifier |
this is not needed ig, not used any where too,can be removed

2021-11-05 18:21 UTC, siva2204 commented on src/controllers/oauthContoller.ts
> +    //check if pkce flow exists(android clients)
this check should be done in token endpoint ig.

2021-11-11 11:01 UTC, siva2204 requested changes
we should think of way to make all the native apps to follow PKCE.

all we need is a proper documentation and examples for PKCE as wells as OAuth.

TODO:
- better documentation
- examples for web and native

2021-11-11 12:24 UTC, nishihere19 commented
Sure, will implement.

2021-11-18 14:22 UTC, siva2204 requested changes

2021-11-18 14:22 UTC, siva2204 commented on src/controllers/oauthContoller.ts
> +        return res.status(400).json({ message: 'Internal server error.' });
return proper error if verification fails, check statandard.

as i can see `verifyCodeChallenge` return bool and throws error.
return `internal server error` if verifyCodeCahellenge throws an error.

2021-11-18 14:22 UTC, siva2204 commented on src/controllers/oauthContoller.ts
> +    if (codeData?.codeChallenge) {
if there is a codeChallenge associated with code(authorization code), and code_verifier is missing in the request return proper error in response.

2021-11-18 14:22 UTC, siva2204 commented on src/utils/oauth.ts
> +    if (codeChallenge) {
its better to create a new utility func to save data regarding to pkce.

2021-11-18 14:23 UTC, siva2204 commented
others looks fine, can merge after these changes.

2021-11-20 18:48 UTC, merged